/** Source-grounded optimization opportunities and limits for evaluation planning.
 * This is descriptive evidence, not an execution registry or an effectiveness claim.
 */
export const optimizationEvidence = [
  {
    id: 'durable-admission-and-oversubscription',
    name: 'Durable admission, bounded leases, and oversubscription',
    complexity: 'Operational bottleneck; SQLite transaction work scales with admitted task/event rows, while writes serialize at the database boundary. Not an NP-hard optimization claim.',
    formulation: 'Admit a dependency DAG with bounded active leases and a run cost reservation; distinguish logical agent identities from active workers and external calls.',
    mitigation: 'Keep the SQLite control plane authoritative for leases, fencing, retries, cancellation, and reservations. Tune active workers separately from logical agents; add provider/resource-specific queues and rate-limit feedback before increasing concurrency.',
    limits: 'ControlStore currently caps a database at 64 active leases and a run at 300 registered agent identities. The deterministic benchmark exercises fixture tasks only; it does not measure provider throughput, quality, or paid-work behavior. SQLite is a local durable queue, not a distributed multi-region scheduler.',
    metrics: ['accepted/rejected admissions and active-lease trace', 'queue wait and end-to-end p50/p95/p99', 'completed tasks per second with task mix fixed', 'SQLite busy/lock time and recovery time', 'duplicate effects, stale-lease fences, unresolved external reconciliation', 'reserved versus actual micro-USD, including retries'],
    kernelEvidence: ['agentic-np-hard-kernel@ad8e99faa20c414b60d86b8ec211863c003535fc: agentic_np_hard_kernel/core/sandbox_resource_scheduler.py::SandboxResourceScheduler.solve is a static lock-timeline ordering heuristic, not the control plane.', 'agentic-graph-swarm-kernel@d429ee702e0e9b59b68f3714723a4f1d4bc425c8: agentic_graph_swarm_kernel/core/disjunctive_tool_scheduler.py::solve_disjunctive_tool_scheduling is ready-queue LPT over one resource ID, not an optimal shifting-bottleneck method.'],
    sources: ['apexgraphswarm/control.py::ControlStore.__init__, create_run, claim, complete, recover_expired, reconcile', 'apexgraphswarm/control.py::MAX_ACTIVE=64, MAX_AGENTS=300', 'scripts/benchmark_swarm.py::run_scenario, _run_wave, _restart_recovery_check'],
  },
  {
    id: 'resource-constrained-scheduling',
    name: 'Resource-constrained task scheduling',
    complexity: 'General precedence-constrained disjunctive/job-shop scheduling is combinatorial; the vendored routines are polynomial greedy heuristics, not exact solvers.',
    formulation: 'Assign ready tasks to scarce tool/sandbox resources while respecting dependencies, durations, exclusivity, and concurrency limits; distinguish this planning model from actual provider quotas and network waits.',
    mitigation: 'Use measured per-resource service distributions, priorities, fairness, backpressure, and retry-safe queues. Compare LPT/critical-path/FCFS against small exact fixtures and an unconstrained lower bound; validate dependency cycles and resource IDs before scheduling.',
    limits: 'AAH20 agentic resource scheduler sorts by lock contention/duration then serializes required locks on timelines; it does not model multi-capacity resources or prove an optimal makespan. Graph-swarm scheduler assigns a single resource per task and can return partial schedules for cycles/unknown predecessors while marking deadlock-free from schedule length. MiroFish event scheduler must be separately tested for cycle and worker-capacity behavior.',
    metrics: ['makespan and critical-path lower-bound gap', 'per-resource busy/idle fraction and queue wait', 'precedence/resource violations (must be zero)', 'starvation/fairness by task class', 'performance across contention skew and burst sizes'],
    kernelEvidence: ['agentic-np-hard-kernel@ad8e99faa20c414b60d86b8ec211863c003535fc: agentic_np_hard_kernel/core/sandbox_resource_scheduler.py::SandboxResourceScheduler.solve', 'agentic-graph-swarm-kernel@d429ee702e0e9b59b68f3714723a4f1d4bc425c8: agentic_graph_swarm_kernel/core/disjunctive_tool_scheduler.py::solve_disjunctive_tool_scheduling', 'mirofish-swarm-optimizer@d2a3df25cf80750fadd562373f7941b9cb8db2f1: mirofish_swarm_optimizer/core/disjunctive_scheduler.py::DisjunctiveEventScheduler.solve'],
    sources: ['scripts/benchmark_swarm.py::DEFAULT_COUNTS, _run_wave (fixture-only concurrency)', 'apexgraphswarm/control.py::ControlStore.claim (leases, not resource-optimal scheduling)'],
  },
  {
    id: 'tool-selection-under-budgets',
    name: 'Tool and model selection under latency/token budgets',
    complexity: 'Dependency-constrained multidimensional knapsack is NP-hard in general. The kernel branch-and-bound search is worst-case exponential; input size and pruning behavior determine practical limits.',
    formulation: 'Choose a subset of candidate tools maximizing declared utility subject to additive latency/token budgets and prerequisite closure. This objective is a proxy, not measured task success or actual billed latency/cost.',
    mitigation: 'Keep candidate inventories small and measured; record model/tool revisions and real usage receipts. Compare branch-and-bound with greedy and exhaustive optima on small instances, then report timeout/optimality gap for larger inventories.',
    limits: 'The vendored implementation precomputes dependency closure and recursively explores include/exclude branches. Its utility upper bound is the sum of remaining utilities; dependency overlap and invalid/cyclic prerequisites need explicit validation. No live provider pricing or quota is learned by this solver.',
    metrics: ['objective gap to exhaustive optimum on small generated cases', 'solver time and nodes expanded by inventory size', 'budget violations and prerequisite closure violations', 'predicted versus observed latency/tokens/cost', 'task success at equal cost and deadline'],
    kernelEvidence: ['agentic-np-hard-kernel@ad8e99faa20c414b60d86b8ec211863c003535fc: agentic_np_hard_kernel/core/tool_routing.py::CombinatorialToolRouter.solve and solve_greedy_baseline'],
    sources: ['apps/web/lib/architecture-benchmark.ts::workloadProfiles (held-out success, cost, latency metrics)', 'apexgraphswarm/control.py::_validate_plan, complete (reservation and settlement are control-plane checks)'],
  },
  {
    id: 'budgeted-graphrag-retrieval',
    name: 'Budgeted GraphRAG context and memory retrieval',
    complexity: 'Budgeted maximum coverage/submodular selection is combinatorial in general. The inspected kernels run greedy scans; no general exactness or approximation guarantee is established by these implementations.',
    formulation: 'Select evidence units or memory records under token limits to trade off coverage/salience and redundancy. The objective must be measured against judged relevance and answer support, not internal diversity scores alone.',
    mitigation: 'Use a deterministic greedy baseline with explicit marginal gain per token, preserve citation/provenance, and evaluate retrieval against held-out relevance labels. Cache embeddings/indexes by corpus revision and bound candidate pools before expensive reranking.',
    limits: 'GraphRAG summarizer recomputes candidate density each round and has a singleton fallback; this is not by itself a proof of a budgeted-knapsack guarantee. Agentic memory lazy greedy uses topic-max coverage plus a min-distance diversity increment, while its reported average pairwise diversity is a different statistic. Graph-swarm attention routing is simple entropy/token sorting per agent, can duplicate a node across agents, and does not use submodular marginal coverage.',
    metrics: ['Recall@k, nDCG@k, citation support and answer correctness on held-out queries', 'token budget compliance and useful-evidence-per-token', 'retrieval p50/p95 plus index build/update time', 'duplicate evidence across agents and context utilization', 'quality/cost at matched token budgets'],
    kernelEvidence: ['graph-rag-np-hard-kernel@35b1bb93a04d419fc1167480d93a1eed711fb711: graph_rag_np_hard_kernel/core/submodular_graph_summary.py::SubmodularGraphSummarizer.solve', 'agentic-np-hard-kernel@ad8e99faa20c414b60d86b8ec211863c003535fc: agentic_np_hard_kernel/core/submodular_memory.py::SubmodularMemoryRetriever.solve', 'agentic-graph-swarm-kernel@d429ee702e0e9b59b68f3714723a4f1d4bc425c8: agentic_graph_swarm_kernel/core/budgeted_attention_routing.py::solve_budgeted_attention_routing'],
    sources: ['apps/web/lib/architecture-benchmark.ts::workloadProfiles["multi-hop-retrieval"]'],
  },
  {
    id: 'query-focused-connected-subgraph',
    name: 'Query-focused connected subgraph extraction',
    complexity: 'Prize-collecting Steiner formulations are NP-hard in general; this kernel is a polynomial seed-rooted greedy expansion and leaf-pruning heuristic, not an exact or validated primal-dual approximation algorithm.',
    formulation: 'Return a connected evidence subgraph balancing node prizes against traversal costs. A single-root expansion can miss valuable disconnected components or alternate routes; connection constraints and edge-weight semantics matter.',
    mitigation: 'Retain seed/query provenance; compare against shortest-path, bounded k-hop, and exact small-graph optima. Handle no seed, disconnected graphs, negative/invalid weights, and no-positive-utility cases explicitly; evaluate connectedness and evidence recall separately.',
    limits: 'Implementation picks a highest-prize root by default, absorbs adjacent nodes under local prize/cost tests, and prunes negative leaves. It does not revisit root/branch choices or optimize global net utility; the source comments claim stronger primal-dual behavior than the code establishes.',
    metrics: ['query evidence recall and answer support', 'net prize-minus-cost against exact optimum on tiny graphs', 'connectedness and edge/node validity', 'latency, traversed edges and output token count', 'sensitivity to seed, disconnected components and edge weights'],
    kernelEvidence: ['graph-rag-np-hard-kernel@35b1bb93a04d419fc1167480d93a1eed711fb711: graph_rag_np_hard_kernel/core/subgraph_extraction.py::PrizeCollectingSteinerTreeSolver.solve'],
    sources: ['apps/web/lib/architecture-benchmark.ts::workloadProfiles["multi-hop-retrieval"]'],
  },
  {
    id: 'graph-partition-and-sparsification',
    name: 'Graph partitioning and graph-size reduction',
    complexity: 'The inspected community method performs bounded greedy modularity moves (roughly per-pass scans of nodes and adjacency); the edge sparsifier sorts edges. These implementations are polynomial heuristics. Graph partitioning and spectral sparsification labels do not establish global optimality or spectral guarantees.',
    formulation: 'Reduce graph neighborhood/search/render cost while retaining useful connectivity and community structure. This is a quality/size tradeoff; downstream retrieval must detect evidence loss.',
    mitigation: 'Treat partitioning and sparsification as optional, versioned preprocessing. Compare retained-edge connectivity, cut/community stability, recall, and downstream answer quality against the original snapshot; retain a route back to unsparsified evidence.',
    limits: 'Community detection makes local node moves for at most max_iterations and does not implement Louvain multilevel coarsening. Sparsifier uses a degree-capped maximum-weight spanning forest followed by high-weight edge insertion; its connectivity ratio is 1/components and no effective-resistance sampling or spectral approximation is computed.',
    metrics: ['retained node/edge counts and preprocessing time/RAM', 'component count, cut stability and community stability', 'retrieval recall and answer quality before/after reduction', 'degree cap violations and spectral error on small graphs'],
    kernelEvidence: ['graph-rag-np-hard-kernel@35b1bb93a04d419fc1167480d93a1eed711fb711: graph_rag_np_hard_kernel/core/community_detection.py::HierarchicalCommunityDetector.solve', 'graph-rag-np-hard-kernel@35b1bb93a04d419fc1167480d93a1eed711fb711: graph_rag_np_hard_kernel/core/spectral_sparsifier.py::SpectralGraphSparsifier.sparsify'],
    sources: ['apps/web/lib/architecture-benchmark.ts::workloadProfiles["multi-hop-retrieval"]'],
  },
  {
    id: 'exact-coalition-search-boundary',
    name: 'Coalition structure optimization boundary',
    complexity: 'The included dynamic program enumerates subsets and proper submasks, giving O(3^n) partition work and O(2^n) value/state storage (with additional coalition-value pairwise work). This is practical only for small n.',
    formulation: 'Partition a finite set of agents into coalitions maximizing an explicit characteristic function. The function encodes assumed influence/cohesion/friction; maximizing it is not evidence that real agents collaborate better.',
    mitigation: 'Use only as a tiny-instance exact oracle or simulation baseline; compare scalable heuristics against it at small n, pin its synthetic utility function, and measure real held-out outcomes before claiming value.',
    limits: 'AAH20 source describes exact coalition structure generation and the implementation really enumerates bitmask subsets/submasks, but model-generated coalition utility is synthetic and the exponential routine is not a general 100/300-agent orchestration solution.',
    metrics: ['runtime/memory by n and exact objective value', 'heuristic objective gap on shared tiny instances', 'real task quality and cost only in a separate held-out evaluation', 'sensitivity to coalition value assumptions'],
    kernelEvidence: ['mirofish-swarm-optimizer@d2a3df25cf80750fadd562373f7941b9cb8db2f1: mirofish_swarm_optimizer/core/coalition_structure.py::OptimalCoalitionStructureSolver.solve, compute_coalition_value'],
    sources: ['.integration-sources/sources.json (pinned revision provenance)'],
  },
  {
    id: 'operational-graph-scale',
    name: 'Graph I/O, context, and visualization scale',
    complexity: 'Operational/memory bandwidth issue, not NP-hard: reading/indexing large graphs, sending context, JSON serialization, and browser rendering can dominate algorithm time.',
    formulation: 'Bound ingest/query/render work while preserving provenance and interaction for graph size N and edge count M; separate server search from client display sampling.',
    mitigation: 'Measure cold ingest, query/index time, bytes/tokens, peak RAM, and client frame timing independently. Use filtered/level-of-detail views for presentation without silently changing the server-side evidence universe.',
    limits: 'The four vendored kernels are in-memory Python implementations and do not establish persistent incremental indexing or browser-scale graph rendering. Current local benchmark is a SHA-256 fixture against SQLite task orchestration, not a GraphRAG or graph-render benchmark.',
    metrics: ['ingest and query p50/p95/p99 by nodes/edges', 'peak RSS/index bytes and serialized bytes', 'context tokens and source coverage', 'browser measured interaction/frame timing on pinned hardware', 'full-graph versus sampled-view evidence parity'],
    kernelEvidence: ['graph-rag-np-hard-kernel@35b1bb93a04d419fc1167480d93a1eed711fb711: graph_rag_np_hard_kernel/core/subgraph_extraction.py (materializes adjacency in memory)', 'agentic-graph-swarm-kernel@d429ee702e0e9b59b68f3714723a4f1d4bc425c8: agentic_graph_swarm_kernel/core/budgeted_attention_routing.py (materializes routed lists and concept sets)'],
    sources: ['scripts/benchmark_swarm.py::fixture_work, run_scenario (not a graph benchmark)', 'docs/apexgraphswarm-evaluation.md (proposed graph retrieval and scaling evaluation protocol)'],
  },
] as const;
