apiVersion: v1
kind: Service
metadata:
  name: apexgraphswarm-web
  namespace: apexgraphswarm
  labels:
    app.kubernetes.io/name: apexgraphswarm
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apexgraphswarm
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  sessionAffinity: None
