"""Detection rules and mitigations for the threat matrix.

Maps each technique to concrete detection logic and mitigation strategies
that align with ApexGraphSwarm's existing security controls.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .matrix import Severity, TacticDomain, ThreatMatrix, build_default_matrix


@dataclass(frozen=True)
class DetectionRule:
    """A detection rule for adversary technique indicators."""
    id: str
    name: str
    description: str
    technique_ids: tuple[str, ...]
    domain: TacticDomain
    severity: Severity
    data_sources: tuple[str, ...]
    detection_logic: str
    false_positive_rate: str  # "low", "medium", "high"
    response_action: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "techniqueIds": list(self.technique_ids),
            "domain": self.domain.value,
            "severity": self.severity.value,
            "dataSources": list(self.data_sources),
            "detectionLogic": self.detection_logic,
            "falsePositiveRate": self.false_positive_rate,
            "responseAction": self.response_action,
        }


@dataclass(frozen=True)
class Mitigation:
    """A mitigation strategy for adversary techniques."""
    id: str
    name: str
    description: str
    technique_ids: tuple[str, ...]
    domain: TacticDomain
    implementation: str
    effectiveness: str  # "preventive", "detective", "corrective"
    coverage_level: str  # "full", "partial", "compensating"

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "techniqueIds": list(self.technique_ids),
            "domain": self.domain.value,
            "implementation": self.implementation,
            "effectiveness": self.effectiveness,
            "coverageLevel": self.coverage_level,
        }


def build_detection_rules() -> list[DetectionRule]:
    """Build the full set of detection rules for all 11 domains."""
    return [
        # Reconnaissance
        DetectionRule(
            id="DETECT-001",
            name="Endpoint Scan Detection",
            description="Detect systematic probing of control-plane endpoints.",
            technique_ids=("RECON-001",),
            domain=TacticDomain.RECONNAISSANCE,
            severity=Severity.HIGH,
            data_sources=("access_logs", "network_flows"),
            detection_logic="Rate of 404/401 responses exceeds threshold from single source.",
            false_positive_rate="low",
            response_action="Alert and rate-limit source.",
        ),
        DetectionRule(
            id="DETECT-002",
            name="Worker Enumeration Detection",
            description="Detect systematic worker ID enumeration attempts.",
            technique_ids=("RECON-002",),
            domain=TacticDomain.RECONNAISSANCE,
            severity=Severity.HIGH,
            data_sources=("auth_logs", "timing_analysis"),
            detection_logic="Authentication timing variance correlates with worker ID sequences.",
            false_positive_rate="medium",
            response_action="Alert and enable constant-time responses.",
        ),
        DetectionRule(
            id="DETECT-003",
            name="Schema Inference Detection",
            description="Detect plan schema inference via malformed submissions.",
            technique_ids=("RECON-003",),
            domain=TacticDomain.RECONNAISSANCE,
            severity=Severity.MEDIUM,
            data_sources=("validation_logs", "error_patterns"),
            detection_logic="High diversity of validation errors from single source.",
            false_positive_rate="medium",
            response_action="Alert and normalize error responses.",
        ),
        DetectionRule(
            id="DETECT-004",
            name="Telemetry Endpoint Mapping Detection",
            description="Detect unauthorized telemetry endpoint access.",
            technique_ids=("RECON-004",),
            domain=TacticDomain.RECONNAISSANCE,
            severity=Severity.MEDIUM,
            data_sources=("metrics_access_logs",),
            detection_logic="Metrics endpoint accessed by non-monitoring service.",
            false_positive_rate="low",
            response_action="Alert and restrict endpoint access.",
        ),
        # Semantic Ingress
        DetectionRule(
            id="DETECT-005",
            name="Prompt Injection Detection",
            description="Detect instruction injection in task payloads.",
            technique_ids=("SEMI-001",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            severity=Severity.CRITICAL,
            data_sources=("payload_analysis", "instruction_classifiers"),
            detection_logic="Payload contains instruction-like patterns that override system prompts.",
            false_positive_rate="medium",
            response_action="Quarantine task and alert.",
        ),
        DetectionRule(
            id="DETECT-006",
            name="Tool Argument Smuggling Detection",
            description="Detect malicious tool arguments that bypass validation.",
            technique_ids=("SEMI-002",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            severity=Severity.CRITICAL,
            data_sources=("tool_argument_analysis", "boundary_checks"),
            detection_logic="Tool arguments contain patterns that violate parameter boundaries.",
            false_positive_rate="low",
            response_action="Reject dispatch and alert.",
        ),
        DetectionRule(
            id="DETECT-007",
            name="Context Overflow Detection",
            description="Detect context window overflow attempts.",
            technique_ids=("SEMI-003",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            severity=Severity.HIGH,
            data_sources=("input_size_monitoring", "truncation_events"),
            detection_logic="Input size approaches or exceeds context window limits.",
            false_positive_rate="low",
            response_action="Reject oversized input and alert.",
        ),
        DetectionRule(
            id="DETECT-008",
            name="Multi-Turn Accumulation Detection",
            description="Detect progressive instruction building across turns.",
            technique_ids=("SEMI-004",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            severity=Severity.HIGH,
            data_sources=("conversation_analysis", "instruction_drift"),
            detection_logic="Cumulative instruction patterns drift from original task intent.",
            false_positive_rate="high",
            response_action="Flag for review and apply stricter validation.",
        ),
        # Context Contamination
        DetectionRule(
            id="DETECT-009",
            name="Knowledge Base Poisoning Detection",
            description="Detect unauthorized modifications to repository graph data.",
            technique_ids=("CTXC-001",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            severity=Severity.CRITICAL,
            data_sources=("graph_integrity_checks", "source_verification"),
            detection_logic="Graph data fails source integrity verification.",
            false_positive_rate="low",
            response_action="Isolate affected data and alert.",
        ),
        DetectionRule(
            id="DETECT-010",
            name="Checkpoint Manipulation Detection",
            description="Detect unauthorized checkpoint modifications.",
            technique_ids=("CTXC-002",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            severity=Severity.HIGH,
            data_sources=("checkpoint_hash_validation", "field_analysis"),
            detection_logic="Checkpoint content fails hash validation or contains unexpected fields.",
            false_positive_rate="low",
            response_action="Reject checkpoint and alert.",
        ),
        DetectionRule(
            id="DETECT-011",
            name="Contract Tampering Detection",
            description="Detect specialist contract scope or approval manipulation.",
            technique_ids=("CTXC-003",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            severity=Severity.CRITICAL,
            data_sources=("contract_validation", "approval_audit"),
            detection_logic="Contract scope drift or approval quorum manipulation detected.",
            false_positive_rate="low",
            response_action="Freeze contract and alert.",
        ),
        DetectionRule(
            id="DETECT-012",
            name="Projection Poisoning Detection",
            description="Detect execution graph projection inconsistencies.",
            technique_ids=("CTXC-004",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            severity=Severity.MEDIUM,
            data_sources=("projection_consistency_checks",),
            detection_logic="Projection data inconsistent with control store status.",
            false_positive_rate="low",
            response_action="Regenerate projection and alert.",
        ),
        # Tool Discipline
        DetectionRule(
            id="DETECT-013",
            name="Unauthorized Tool Invocation Detection",
            description="Detect tool calls outside granted capability scope.",
            technique_ids=("TOOL-001",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            severity=Severity.CRITICAL,
            data_sources=("access_grant_validation", "dispatch_logs"),
            detection_logic="Tool invocation lacks valid exact capability grant.",
            false_positive_rate="low",
            response_action="Reject dispatch and alert.",
        ),
        DetectionRule(
            id="DETECT-014",
            name="Budget Exhaustion Detection",
            description="Detect rapid grant budget consumption patterns.",
            technique_ids=("TOOL-002",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            severity=Severity.HIGH,
            data_sources=("spend_rate_monitoring", "budget_tracking"),
            detection_logic="Spend rate exceeds normal operational thresholds.",
            false_positive_rate="medium",
            response_action="Rate-limit and alert.",
        ),
        DetectionRule(
            id="DETECT-015",
            name="Output Forgery Detection",
            description="Detect fabricated tool results or receipts.",
            technique_ids=("TOOL-003",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            severity=Severity.CRITICAL,
            data_sources=("receipt_validation", "output_hash_checks"),
            detection_logic="Tool output fails receipt validation or hash verification.",
            false_positive_rate="low",
            response_action="Reject output and alert.",
        ),
        DetectionRule(
            id="DETECT-016",
            name="Lease Token Theft Detection",
            description="Detect lease token reuse or forgery.",
            technique_ids=("TOOL-004",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            severity=Severity.CRITICAL,
            data_sources=("lease_validation", "token_binding_checks"),
            detection_logic="Lease token used from different worker than original claimant.",
            false_positive_rate="low",
            response_action="Revoke lease and alert.",
        ),
        # Sandbox Escape
        DetectionRule(
            id="DETECT-017",
            name="Subprocess Boundary Violation Detection",
            description="Detect command execution outside subprocess isolation.",
            technique_ids=("SBEX-001",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            severity=Severity.CRITICAL,
            data_sources=("process_monitoring", "argument_analysis"),
            detection_logic="Shell metacharacters or unsafe deserialization in subprocess arguments.",
            false_positive_rate="low",
            response_action="Kill process and alert.",
        ),
        DetectionRule(
            id="DETECT-018",
            name="Namespace Escape Detection",
            description="Detect file system namespace boundary violations.",
            technique_ids=("SBEX-002",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            severity=Severity.CRITICAL,
            data_sources=("vfs_monitoring", "path_validation"),
            detection_logic="File access outside VFS namespace boundaries.",
            false_positive_rate="low",
            response_action="Block access and alert.",
        ),
        DetectionRule(
            id="DETECT-019",
            name="Network Escape Detection",
            description="Detect unauthorized network egress from sandbox.",
            technique_ids=("SBEX-003",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            severity=Severity.HIGH,
            data_sources=("network_monitoring", "egress_policy_checks"),
            detection_logic="Outbound connections violate egress policy.",
            false_positive_rate="low",
            response_action="Block connection and alert.",
        ),
        DetectionRule(
            id="DETECT-020",
            name="Ring Transition Exploit Detection",
            description="Detect unauthorized ring transitions.",
            technique_ids=("SBEX-004",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            severity=Severity.CRITICAL,
            data_sources=("ring_policy_monitoring", "transition_validation"),
            detection_logic="Ring transition violates policy or lacks authorization.",
            false_positive_rate="low",
            response_action="Block transition and alert.",
        ),
        # Privilege Escalation
        DetectionRule(
            id="DETECT-021",
            name="Identity Spoofing Detection",
            description="Detect worker credential forgery or theft.",
            technique_ids=("PRIV-001",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            severity=Severity.CRITICAL,
            data_sources=("credential_validation", "identity_binding"),
            detection_logic="Credential used from different worker than enrolled.",
            false_positive_rate="low",
            response_action="Revoke credential and alert.",
        ),
        DetectionRule(
            id="DETECT-022",
            name="Principal Impersonation Detection",
            description="Detect cross-principal activity.",
            technique_ids=("PRIV-002",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            severity=Severity.CRITICAL,
            data_sources=("principal_validation", "grant_scope_checks"),
            detection_logic="Activity associated with principal different from authenticated identity.",
            false_positive_rate="low",
            response_action="Reject action and alert.",
        ),
        DetectionRule(
            id="DETECT-023",
            name="Quorum Bypass Detection",
            description="Detect approval quorum manipulation.",
            technique_ids=("PRIV-003",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            severity=Severity.HIGH,
            data_sources=("approval_audit", "principal_uniqueness"),
            detection_logic="Multiple workers for same principal satisfy quorum.",
            false_positive_rate="low",
            response_action="Invalidate approvals and alert.",
        ),
        DetectionRule(
            id="DETECT-024",
            name="Revocation Timing Detection",
            description="Detect actions after revocation timestamp.",
            technique_ids=("PRIV-004",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            severity=Severity.MEDIUM,
            data_sources=("revocation_audit", "action_timing"),
            detection_logic="Action timestamp after revocation timestamp.",
            false_positive_rate="low",
            response_action="Reject action and alert.",
        ),
        # Swarm Contagion
        DetectionRule(
            id="DETECT-025",
            name="Cross-Worker Contamination Detection",
            description="Detect state poisoning across workers.",
            technique_ids=("SWAR-001",),
            domain=TacticDomain.SWARM_CONTAGION,
            severity=Severity.CRITICAL,
            data_sources=("state_integrity_checks", "cross_task_analysis"),
            detection_logic="Shared state shows corruption patterns across multiple workers.",
            false_positive_rate="medium",
            response_action="Isolate affected workers and alert.",
        ),
        DetectionRule(
            id="DETECT-026",
            name="Delegation Hijack Detection",
            description="Detect delegation plan manipulation.",
            technique_ids=("SWAR-002",),
            domain=TacticDomain.SWARM_CONTAGION,
            severity=Severity.HIGH,
            data_sources=("delegation_validation", "routing_analysis"),
            detection_logic="Delegation targets deviate from expected routing.",
            false_positive_rate="medium",
            response_action="Reject delegation and alert.",
        ),
        DetectionRule(
            id="DETECT-027",
            name="Consensus Disruption Detection",
            description="Detect consensus protocol attacks.",
            technique_ids=("SWAR-003",),
            domain=TacticDomain.SWARM_CONTAGION,
            severity=Severity.CRITICAL,
            data_sources=("consensus_monitoring", "ballot_analysis"),
            detection_logic="Ballot conflicts or leader election instability detected.",
            false_positive_rate="low",
            response_action="Initiate recovery and alert.",
        ),
        DetectionRule(
            id="DETECT-028",
            name="Contract Scope Propagation Detection",
            description="Detect contract scope expansion across workers.",
            technique_ids=("SWAR-004",),
            domain=TacticDomain.SWARM_CONTAGION,
            severity=Severity.HIGH,
            data_sources=("contract_binding_analysis", "scope_validation"),
            detection_logic="Contract bound to multiple workers beyond approved scope.",
            false_positive_rate="low",
            response_action="Revoke contract and alert.",
        ),
        # Telemetry Suppression
        DetectionRule(
            id="DETECT-029",
            name="Metrics Flooding Detection",
            description="Detect telemetry endpoint flooding.",
            technique_ids=("TELX-001",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            severity=Severity.HIGH,
            data_sources=("metrics_access_monitoring",),
            detection_logic="Metrics scrape rate exceeds normal thresholds.",
            false_positive_rate="low",
            response_action="Rate-limit and alert.",
        ),
        DetectionRule(
            id="DETECT-030",
            name="Ledger Suppression Detection",
            description="Detect missing or delayed ledger entries.",
            technique_ids=("TELX-002",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            severity=Severity.CRITICAL,
            data_sources=("ledger_integrity_checks", "settlement_monitoring"),
            detection_logic="Expected ledger entries missing or settlement gaps detected.",
            false_positive_rate="low",
            response_action="Alert and initiate reconciliation.",
        ),
        DetectionRule(
            id="DETECT-031",
            name="Log Injection Detection",
            description="Detect misleading log entries.",
            technique_ids=("TELX-003",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            severity=Severity.MEDIUM,
            data_sources=("log_format_validation", "alert_threshold_monitoring"),
            detection_logic="Log format anomalies or alert threshold manipulation.",
            false_positive_rate="medium",
            response_action="Flag logs and alert.",
        ),
        DetectionRule(
            id="DETECT-032",
            name="Analytics Poisoning Detection",
            description="Detect analytics data corruption.",
            technique_ids=("TELX-004",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            severity=Severity.MEDIUM,
            data_sources=("analytics_validation", "forecast_consistency"),
            detection_logic="Analytics data shows inconsistencies with raw ledger data.",
            false_positive_rate="medium",
            response_action="Regenerate analytics and alert.",
        ),
        # Financial Rail
        DetectionRule(
            id="DETECT-033",
            name="Budget Manipulation Detection",
            description="Detect cost reservation manipulation.",
            technique_ids=("FINR-001",),
            domain=TacticDomain.FINANCIAL_RAIL,
            severity=Severity.CRITICAL,
            data_sources=("budget_audit", "reservation_tracking"),
            detection_logic="Reservation patterns indicate budget control bypass.",
            false_positive_rate="low",
            response_action="Freeze budget and alert.",
        ),
        DetectionRule(
            id="DETECT-034",
            name="Receipt Forgery Detection",
            description="Detect forged provider receipts.",
            technique_ids=("FINR-002",),
            domain=TacticDomain.FINANCIAL_RAIL,
            severity=Severity.CRITICAL,
            data_sources=("receipt_validation", "cost_reconciliation"),
            detection_logic="Receipt fails validation or reconciliation checks.",
            false_positive_rate="low",
            response_action="Reject receipt and alert.",
        ),
        DetectionRule(
            id="DETECT-035",
            name="Double-Spend Detection",
            description="Detect grant budget double-spend attempts.",
            technique_ids=("FINR-003",),
            domain=TacticDomain.FINANCIAL_RAIL,
            severity=Severity.HIGH,
            data_sources=("concurrent_spend_tracking", "race_condition_analysis"),
            detection_logic="Concurrent budget consumption exceeds grant limits.",
            false_positive_rate="low",
            response_action="Reject overspend and alert.",
        ),
        DetectionRule(
            id="DETECT-036",
            name="Cost Telemetry Manipulation Detection",
            description="Detect cost telemetry corruption.",
            technique_ids=("FINR-004",),
            domain=TacticDomain.FINANCIAL_RAIL,
            severity=Severity.HIGH,
            data_sources=("cost_telemetry_validation", "financial_metric_analysis"),
            detection_logic="Cost telemetry inconsistent with ledger data.",
            false_positive_rate="medium",
            response_action="Alert and reconcile.",
        ),
        # State Exfiltration
        DetectionRule(
            id="DETECT-037",
            name="Credential Exfiltration Detection",
            description="Detect credential extraction via tool output.",
            technique_ids=("EXFX-001",),
            domain=TacticDomain.STATE_EXFILTRATION,
            severity=Severity.CRITICAL,
            data_sources=("output_analysis", "credential_pattern_matching"),
            detection_logic="Tool output contains credential or token patterns.",
            false_positive_rate="low",
            response_action="Block output and alert.",
        ),
        DetectionRule(
            id="DETECT-038",
            name="Payload Exfiltration Detection",
            description="Detect task payload extraction.",
            technique_ids=("EXFX-002",),
            domain=TacticDomain.STATE_EXFILTRATION,
            severity=Severity.HIGH,
            data_sources=("projection_analysis", "data_access_monitoring"),
            detection_logic="Projection or analytics contains unauthorized payload data.",
            false_positive_rate="low",
            response_action="Restrict access and alert.",
        ),
        DetectionRule(
            id="DETECT-039",
            name="Contract Data Theft Detection",
            description="Detect specialist contract data extraction.",
            technique_ids=("EXFX-003",),
            domain=TacticDomain.STATE_EXFILTRATION,
            severity=Severity.HIGH,
            data_sources=("contract_access_audit", "scope_validation"),
            detection_logic="Contract data accessed outside authorized scope.",
            false_positive_rate="low",
            response_action="Revoke access and alert.",
        ),
        DetectionRule(
            id="DETECT-040",
            name="Side-Channel Leakage Detection",
            description="Detect information leakage via side channels.",
            technique_ids=("EXFX-004",),
            domain=TacticDomain.STATE_EXFILTRATION,
            severity=Severity.MEDIUM,
            data_sources=("timing_analysis", "error_message_analysis"),
            detection_logic="Timing or error patterns correlate with sensitive data access.",
            false_positive_rate="high",
            response_action="Flag for investigation.",
        ),
        # Resource Exhaustion
        DetectionRule(
            id="DETECT-041",
            name="Task Flood Detection",
            description="Detect task creation flood attacks.",
            technique_ids=("RSRX-001",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            severity=Severity.HIGH,
            data_sources=("task_creation_monitoring", "capacity_tracking"),
            detection_logic="Task creation rate exceeds operational thresholds.",
            false_positive_rate="low",
            response_action="Rate-limit and alert.",
        ),
        DetectionRule(
            id="DETECT-042",
            name="Checkpoint Exhaustion Detection",
            description="Detect checkpoint storage exhaustion.",
            technique_ids=("RSRX-002",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            severity=Severity.MEDIUM,
            data_sources=("checkpoint_monitoring", "storage_tracking"),
            detection_logic="Checkpoint count or size approaches limits.",
            false_positive_rate="low",
            response_action="Reject new checkpoints and alert.",
        ),
        DetectionRule(
            id="DETECT-043",
            name="Lease Exhaustion Detection",
            description="Detect lease holding attacks.",
            technique_ids=("RSRX-003",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            severity=Severity.HIGH,
            data_sources=("lease_monitoring", "heartbeat_tracking"),
            detection_logic="Leases held without heartbeat approach MAX_ACTIVE.",
            false_positive_rate="low",
            response_action="Reclaim leases and alert.",
        ),
        DetectionRule(
            id="DETECT-044",
            name="Consensus Flooding Detection",
            description="Detect consensus log flooding.",
            technique_ids=("RSRX-004",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            severity=Severity.MEDIUM,
            data_sources=("consensus_monitoring", "log_growth_tracking"),
            detection_logic="Consensus log growth rate exceeds normal thresholds.",
            false_positive_rate="low",
            response_action="Rate-limit and alert.",
        ),
    ]


def build_mitigations() -> list[Mitigation]:
    """Build the full set of mitigations for all 11 domains."""
    return [
        # Reconnaissance mitigations
        Mitigation(
            id="MITIG-001",
            name="Endpoint Access Control",
            description="Restrict control-plane endpoint access to authorized sources.",
            technique_ids=("RECON-001",),
            domain=TacticDomain.RECONNAISSANCE,
            implementation="Network-level access control and authentication required for all endpoints.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-002",
            name="Constant-Time Authentication",
            description="Ensure authentication responses have constant timing regardless of worker ID validity.",
            technique_ids=("RECON-002",),
            domain=TacticDomain.RECONNAISSANCE,
            implementation="Use hmac.compare_digest and fixed-length comparison on absent-identity path.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-003",
            name="Normalized Error Responses",
            description="Return uniform error messages for all validation failures.",
            technique_ids=("RECON-003",),
            domain=TacticDomain.RECONNAISSANCE,
            implementation="Map all validation errors to a single generic error response.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-004",
            name="Telemetry Endpoint Protection",
            description="Restrict telemetry endpoint access to monitoring services.",
            technique_ids=("RECON-004",),
            domain=TacticDomain.RECONNAISSANCE,
            implementation="Network policies and authentication for metrics endpoints.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        # Semantic Ingress mitigations
        Mitigation(
            id="MITIG-005",
            name="Instruction Boundary Enforcement",
            description="Enforce clear boundaries between system instructions and user content.",
            technique_ids=("SEMI-001",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            implementation="Validate task payloads for instruction-like patterns and enforce role separation.",
            effectiveness="preventive",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-006",
            name="Tool Argument Validation",
            description="Strict validation of all tool arguments against parameter schemas.",
            technique_ids=("SEMI-002",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            implementation="Schema-based validation with boundary checks for all tool parameters.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-007",
            name="Context Window Limits",
            description="Enforce strict context window size limits.",
            technique_ids=("SEMI-003",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            implementation="Reject inputs that exceed context window capacity.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-008",
            name="Multi-Turn Monitoring",
            description="Monitor conversation patterns for instruction drift.",
            technique_ids=("SEMI-004",),
            domain=TacticDomain.SEMANTIC_INGRESS,
            implementation="Track cumulative instruction patterns and flag drift from original intent.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        # Context Contamination mitigations
        Mitigation(
            id="MITIG-009",
            name="Source Integrity Verification",
            description="Verify knowledge base data against source integrity checks.",
            technique_ids=("CTXC-001",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            implementation="Hash-based verification of graph data against source repository.",
            effectiveness="detective",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-010",
            name="Checkpoint Integrity Protection",
            description="Protect checkpoint data with hash validation and field restrictions.",
            technique_ids=("CTXC-002",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            implementation="Hash validation and strict field schema enforcement for checkpoints.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-011",
            name="Contract Scope Enforcement",
            description="Enforce specialist contract scope and approval requirements.",
            technique_ids=("CTXC-003",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            implementation="Exact scope node validation and quorum-based approval enforcement.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-012",
            name="Projection Consistency Checks",
            description="Verify execution graph projection consistency with control store.",
            technique_ids=("CTXC-004",),
            domain=TacticDomain.CONTEXT_CONTAMINATION,
            implementation="Regular consistency validation between projections and control store status.",
            effectiveness="detective",
            coverage_level="full",
        ),
        # Tool Discipline mitigations
        Mitigation(
            id="MITIG-013",
            name="Capability-Based Access Control",
            description="Enforce exact capability grants for all tool invocations.",
            technique_ids=("TOOL-001",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            implementation="Exact tuple (principal, tool, resource) grant validation at dispatch time.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-014",
            name="Budget Rate Limiting",
            description="Rate-limit grant budget consumption.",
            technique_ids=("TOOL-002",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            implementation="Spend rate monitoring with automatic rate limiting.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-015",
            name="Receipt Validation",
            description="Validate all tool output receipts before acceptance.",
            technique_ids=("TOOL-003",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            implementation="Cryptographic receipt validation and output hash verification.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-016",
            name="Lease Token Binding",
            description="Bind lease tokens to specific workers.",
            technique_ids=("TOOL-004",),
            domain=TacticDomain.TOOL_DISCIPLINE,
            implementation="Worker ID validation on all lease operations.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        # Sandbox Escape mitigations
        Mitigation(
            id="MITIG-017",
            name="Subprocess Isolation",
            description="Enforce strict subprocess isolation with argument validation.",
            technique_ids=("SBEX-001",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            implementation="No shell interpretation, strict argument schema validation.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-018",
            name="VFS Namespace Enforcement",
            description="Enforce file system namespace boundaries.",
            technique_ids=("SBEX-002",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            implementation="Path validation and namespace isolation for all file operations.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-019",
            name="Network Egress Policy",
            description="Enforce network egress policies for sandboxed processes.",
            technique_ids=("SBEX-003",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            implementation="Default-deny egress with explicit allowlist.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-020",
            name="Ring Policy Enforcement",
            description="Enforce ring transition policies.",
            technique_ids=("SBEX-004",),
            domain=TacticDomain.SANDBOX_ESCAPE,
            implementation="Policy validation and authorization for all ring transitions.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        # Privilege Escalation mitigations
        Mitigation(
            id="MITIG-021",
            name="Credential Binding",
            description="Bind credentials to specific worker identities.",
            technique_ids=("PRIV-001",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            implementation="Worker ID validation on all credential use.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-022",
            name="Principal Validation",
            description="Validate principal identity on all operations.",
            technique_ids=("PRIV-002",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            implementation="Principal ID consistency checks across all authenticated operations.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-023",
            name="Quorum Uniqueness",
            description="Enforce principal uniqueness in approval quorum.",
            technique_ids=("PRIV-003",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            implementation="Deduplicate approvals by principal ID, not worker ID.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-024",
            name="Revocation Enforcement",
            description="Enforce revocation immediately at check time.",
            technique_ids=("PRIV-004",),
            domain=TacticDomain.PRIVILEGE_ESCALATION,
            implementation="Check revocation status on every authenticated operation.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        # Swarm Contagion mitigations
        Mitigation(
            id="MITIG-025",
            name="State Isolation",
            description="Isolate state between workers.",
            technique_ids=("SWAR-001",),
            domain=TacticDomain.SWARM_CONTAGION,
            implementation="Per-worker state isolation with integrity validation.",
            effectiveness="preventive",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-026",
            name="Delegation Validation",
            description="Validate delegation plan integrity.",
            technique_ids=("SWAR-002",),
            domain=TacticDomain.SWARM_CONTAGION,
            implementation="Delegation target validation and routing verification.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-027",
            name="Consensus Hardening",
            description="Harden consensus protocol against disruption.",
            technique_ids=("SWAR-003",),
            domain=TacticDomain.SWARM_CONTAGION,
            implementation="Byzantine fault tolerance and leader election stability mechanisms.",
            effectiveness="preventive",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-028",
            name="Contract Binding Limits",
            description="Limit contract scope to approved workers.",
            technique_ids=("SWAR-004",),
            domain=TacticDomain.SWARM_CONTAGION,
            implementation="Strict contract-to-worker binding validation.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        # Telemetry Suppression mitigations
        Mitigation(
            id="MITIG-029",
            name="Metrics Rate Limiting",
            description="Rate-limit metrics endpoint access.",
            technique_ids=("TELX-001",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            implementation="Request rate limiting and anomaly detection for metrics access.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-030",
            name="Ledger Integrity Monitoring",
            description="Monitor ledger entry completeness.",
            technique_ids=("TELX-002",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            implementation="Automated reconciliation and missing entry detection.",
            effectiveness="detective",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-031",
            name="Log Format Validation",
            description="Validate log entry format and content.",
            technique_ids=("TELX-003",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            implementation="Strict log schema validation and anomaly detection.",
            effectiveness="detective",
            coverage_level="partial",
        ),
        Mitigation(
            id="MITIG-032",
            name="Analytics Validation",
            description="Validate analytics data against raw ledger.",
            technique_ids=("TELX-004",),
            domain=TacticDomain.TELEMETRY_SUPPRESSION,
            implementation="Cross-validation of analytics output against source ledger data.",
            effectiveness="detective",
            coverage_level="full",
        ),
        # Financial Rail mitigations
        Mitigation(
            id="MITIG-033",
            name="Budget Control Enforcement",
            description="Enforce strict budget controls at admission.",
            technique_ids=("FINR-001",),
            domain=TacticDomain.FINANCIAL_RAIL,
            implementation="Integer micro-USD validation and reservation enforcement.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-034",
            name="Receipt Cryptographic Validation",
            description="Cryptographically validate all provider receipts.",
            technique_ids=("FINR-002",),
            domain=TacticDomain.FINANCIAL_RAIL,
            implementation="Signature verification and reconciliation for all receipts.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-035",
            name="Atomic Budget Tracking",
            description="Use atomic operations for budget tracking.",
            technique_ids=("FINR-003",),
            domain=TacticDomain.FINANCIAL_RAIL,
            implementation="SQLite transactions with proper isolation for all budget operations.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-036",
            name="Cost Telemetry Reconciliation",
            description="Reconcile cost telemetry with ledger data.",
            technique_ids=("FINR-004",),
            domain=TacticDomain.FINANCIAL_RAIL,
            implementation="Automated reconciliation between cost telemetry and ledger entries.",
            effectiveness="detective",
            coverage_level="full",
        ),
        # State Exfiltration mitigations
        Mitigation(
            id="MITIG-037",
            name="Output Sanitization",
            description="Sanitize tool outputs to remove credentials.",
            technique_ids=("EXFX-001",),
            domain=TacticDomain.STATE_EXFILTRATION,
            implementation="Pattern-based detection and redaction of credentials in outputs.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-038",
            name="Projection Data Minimization",
            description="Minimize data in execution graph projections.",
            technique_ids=("EXFX-002",),
            domain=TacticDomain.STATE_EXFILTRATION,
            implementation="Exclude payloads, results, and credentials from projections.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-039",
            name="Contract Access Control",
            description="Restrict specialist contract data access.",
            technique_ids=("EXFX-003",),
            domain=TacticDomain.STATE_EXFILTRATION,
            implementation="Scope-based access control for contract data.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-040",
            name="Side-Channel Hardening",
            description="Harden against timing and error-based side channels.",
            technique_ids=("EXFX-004",),
            domain=TacticDomain.STATE_EXFILTRATION,
            implementation="Constant-time operations and normalized error responses.",
            effectiveness="preventive",
            coverage_level="partial",
        ),
        # Resource Exhaustion mitigations
        Mitigation(
            id="MITIG-041",
            name="Task Rate Limiting",
            description="Rate-limit task creation.",
            technique_ids=("RSRX-001",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            implementation="Task creation rate limits and capacity monitoring.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-042",
            name="Checkpoint Limits",
            description="Enforce checkpoint count and size limits.",
            technique_ids=("RSRX-002",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            implementation="MAX_CHECKPOINTS_PER_ATTEMPT and MAX_CHECKPOINT_TOTAL_BYTES enforcement.",
            effectiveness="preventive",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-043",
            name="Lease Reaper",
            description="Automatically reclaim expired leases.",
            technique_ids=("RSRX-003",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            implementation="Background lease expiration and reclamation.",
            effectiveness="corrective",
            coverage_level="full",
        ),
        Mitigation(
            id="MITIG-044",
            name="Consensus Log Limits",
            description="Limit consensus log growth.",
            technique_ids=("RSRX-004",),
            domain=TacticDomain.RESOURCE_EXHAUSTION,
            implementation="Log compaction and growth rate monitoring.",
            effectiveness="preventive",
            coverage_level="partial",
        ),
    ]
