'use client';
import {useEffect,useId,useMemo,useRef,useState} from 'react';
import {Maximize2,RefreshCw,Download,Search,ZoomIn,ZoomOut} from 'lucide-react';
import {downloadJSON} from '@/lib/graph';
import {formatMicrousd} from '@/lib/format-microusd';
import {EXECUTION_KINDS,executionLayout,executionView,type ExecutionGraph} from '@/lib/execution-graph';
import styles from './ExecutionTrace.module.css';

export default function ExecutionTrace({runId,token}:{runId:string;token:string}){
 const [graph,setGraph]=useState<ExecutionGraph|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[selected,setSelected]=useState<string|null>(null),[neighbors,setNeighbors]=useState(false),[zoom,setZoom]=useState(1),[expanded,setExpanded]=useState(false),[fullscreen,setFullscreen]=useState(false);
 const panel=useRef<HTMLElement>(null),request=useRef<AbortController|null>(null),marker=useId().replace(/:/g,'');
 useEffect(()=>()=>request.current?.abort(),[]);
 useEffect(()=>{const update=()=>setFullscreen(document.fullscreenElement===panel.current);document.addEventListener('fullscreenchange',update);return ()=>document.removeEventListener('fullscreenchange',update);},[]);
 async function load(){request.current?.abort();const controller=new AbortController();request.current=controller;setBusy(true);setError('');try{const response=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({action:'executionGraph',runId}),signal:controller.signal});const body=await response.json();if(!response.ok)throw Error(body.error||'Execution graph unavailable.');if(request.current!==controller)return;setGraph(body.state);setSelected(previous=>body.state.nodes.some((n:{id:string})=>n.id===previous)?previous:null);}catch(cause){if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:'Execution graph unavailable.');}finally{if(request.current===controller)setBusy(false);}}
 const view=useMemo(()=>graph?executionView(graph,query,kind,selected,neighbors):null,[graph,query,kind,selected,neighbors]);
 const layout=useMemo(()=>executionLayout(view?.nodes||[]),[view]);
 const chosen=graph?.nodes.find(node=>node.id===selected),relations=graph?.edges.filter(edge=>edge.source===selected||edge.target===selected)||[];
 const byId=useMemo(()=>new Map(graph?.nodes.map(node=>[node.id,node])||[]),[graph]);
 function focus(id:string){setSelected(id);setKind('all');setQuery('');setNeighbors(true);}
 async function fullScreen(){try{if(document.fullscreenElement===panel.current){await document.exitFullscreen();}else if(panel.current?.requestFullscreen){await panel.current.requestFullscreen();}else setExpanded(value=>!value);}catch{setExpanded(value=>!value);}}
 return <section ref={panel} className={`${styles.panel} ${expanded?styles.expanded:''}`} aria-label="Execution explanation graph">
  <div className={styles.heading}><div><span className="eyebrow">EXECUTION / COST / CONSTRAINTS</span><h3>Follow the evidence.</h3><p>Trace a persisted run through tasks, attempts and authorization. This view performs no execution.</p></div><div className={styles.actions}><button className="secondary-button" disabled={busy||!token} onClick={()=>void load()}><RefreshCw size={14}/>{busy?'Loading…':graph?'Refresh graph':'Load execution graph'}</button><button className="secondary-button" onClick={()=>void fullScreen()}><Maximize2 size={14}/>{fullscreen?'Exit full screen':expanded?'Exit expanded view':'Full screen'}</button>{graph&&<button className="secondary-button" onClick={()=>downloadJSON('apexgraphswarm-execution-graph.json',graph)}><Download size={14}/>Export graph</button>}</div></div>
  {error&&<p role="alert" className="error-text">{error}</p>}
  {!graph&&!busy&&<p className="apex-note">Load the stored relationships and cost evidence for this run. No model credentials or checkpoint bodies are included.</p>}
  {graph&&view&&<><div className="apex-metrics"><div><strong>{graph.summary.nodeCount}</strong><span>Returned evidence nodes</span></div><div><strong>{formatMicrousd(graph.summary.knownActualMicrousd)}</strong><span>Known attempt cost</span></div><div><strong>{graph.summary.unknownCostAttempts}</strong><span>Attempts with unknown cost</span></div><div><strong>{graph.summary.allCostsResolved?'Resolved':'Incomplete'}</strong><span>Recorded cost coverage</span></div></div>
   <div className={styles.filters}><label><Search size={14}/>Search evidence<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Task, worker, state or ID"/></label><label>Node type<select value={kind} onChange={event=>setKind(event.target.value)}><option value="all">All types</option>{EXECUTION_KINDS.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={neighbors} disabled={!selected} onChange={event=>setNeighbors(event.target.checked)}/>Selected neighborhood</label><button className="secondary-button" aria-label="Zoom out execution graph" onClick={()=>setZoom(value=>Math.max(.5,value-.15))}><ZoomOut size={14}/></button><span>{Math.round(zoom*100)}%</span><button className="secondary-button" aria-label="Zoom in execution graph" onClick={()=>setZoom(value=>Math.min(2,value+.15))}><ZoomIn size={14}/></button></div>
   <p role="status" className="apex-note">Showing {view.nodes.length} of {view.matched} matching nodes and {view.edges.length} relationships. {view.omitted>0?'Narrow the search to inspect omitted nodes. ':''}{graph.truncated?'The server projection is truncated; exported evidence declares the omissions. ':''}Layout groups evidence by type; horizontal position is not elapsed time.</p>
   <div className={styles.workspace}><div><div className={styles.canvas} tabIndex={0} aria-label="Scrollable execution graph"><svg width={layout.width*zoom} height={layout.height*zoom} viewBox={`0 0 ${layout.width} ${layout.height}`} role="group" aria-label="Persisted execution relationships"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#667b83"/></marker></defs>{layout.kinds.map((value,i)=><text key={value} x={30+i*245} y={25} className={styles.column}>{value.toUpperCase()}</text>)}{view.edges.map(edge=>{const a=layout.positions.get(edge.source),b=layout.positions.get(edge.target);if(!a||!b)return null;return <path key={edge.id} d={a.x===b.x?`M ${a.x+218} ${a.y+28} C ${a.x+242} ${a.y+28}, ${b.x+242} ${b.y+28}, ${b.x+218} ${b.y+28}`:`M ${a.x+(b.x>a.x?218:0)} ${a.y+28} C ${a.x+(b.x>a.x?238:-20)} ${a.y+28}, ${b.x+(b.x>a.x?-20:238)} ${b.y+28}, ${b.x+(b.x>a.x?0:218)} ${b.y+28}`} fill="none" stroke={edge.source===selected||edge.target===selected?'#285f52':'#c4cfd3'} strokeWidth={edge.source===selected||edge.target===selected?2:1} markerEnd={`url(#${marker})`}><title>{edge.kind}: {byId.get(edge.source)?.label} → {byId.get(edge.target)?.label}</title></path>;})}{view.nodes.map(node=>{const point=layout.positions.get(node.id);if(!point)return null;return <g key={node.id} role="button" tabIndex={0} aria-label={`${node.kind}: ${node.label}, ${node.status||'evidence'}`} aria-pressed={selected===node.id} onClick={()=>setSelected(node.id)} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();setSelected(node.id);}}} className={styles.node} transform={`translate(${point.x},${point.y})`}><rect width="218" height="58" rx="10" fill={selected===node.id?'#e0f1e9':'#fff'} stroke={selected===node.id?'#285f52':'#b8c9c4'} strokeWidth={selected===node.id?2:1}/><text x="12" y="23">{node.label.length>28?node.label.slice(0,27)+'…':node.label}</text><text x="12" y="43" className={styles.status}>{node.status||node.kind}</text><title>{node.id}</title></g>;})}</svg></div>{view.nodes.length===0&&<p>No nodes match these filters. Clear the search or select another type.</p>}<details className={styles.list}><summary>Accessible node list ({view.nodes.length})</summary><div>{view.nodes.map(node=><button key={node.id} className="text-button" onClick={()=>setSelected(node.id)}>{node.kind} · {node.label} · {node.status||'evidence'}</button>)}</div></details></div>
   <aside className={styles.detail} aria-live="polite">{chosen?<><span className="eyebrow">{chosen.kind}</span><h4>{chosen.label}</h4><code>{chosen.id}</code>{chosen.status&&<p>Status: <strong>{chosen.status}</strong></p>}{'reservedMicrousd' in chosen&&<p>Reserved: {formatMicrousd(chosen.reservedMicrousd??null)}</p>}{'actualMicrousd' in chosen&&<p>Actual: {formatMicrousd(chosen.actualMicrousd??null)}</p>}{chosen.explanations?.map((item,index)=><p key={index}>{item}</p>)}<h4>Connected evidence</h4>{relations.length?relations.slice(0,50).map(edge=>{const other=edge.source===selected?edge.target:edge.source;return <button key={edge.id} className="text-button" onClick={()=>focus(other)}>{edge.source===selected?'→':'←'} {edge.kind.replaceAll('_',' ')} · {byId.get(other)?.label||other}</button>;}):<p>No returned relationships.</p>}{relations.length>50&&<p>Showing 50 of {relations.length} relationships; export includes the returned graph.</p>}<details><summary>Attribution details</summary><pre className="apex-json">{JSON.stringify(chosen.details||{},null,2)}</pre></details></>:<><h4>Inspect an evidence node</h4><p>Select a task, attempt, worker or grant to see its recorded connections and constraints.</p><p>Unknown costs remain unknown. Edges show recorded attribution, not proof of current permission or provider invoice reconciliation.</p></>}</aside></div>
   <details className={styles.limitations}><summary>Evidence limits and omissions</summary><ul>{graph.limitations.map((limit,i)=><li key={i}>{limit}</li>)}</ul><pre className="apex-json">{JSON.stringify(graph.summary,null,2)}</pre></details>
  </>}
 </section>;
}
