import RepositoryConflictResults from './RepositoryConflictResults';
import {formatMicrousd as money} from '@/lib/format-microusd';
type Row=Record<string,unknown>;
const records=(value:unknown):Row[]=>Array.isArray(value)?value.filter((item):item is Row=>!!item&&typeof item==='object'&&!Array.isArray(item)):[];
const object=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
export default function OptimizationResults({result}:{result:Row}){
 const assignments=records(result.assignments ?? object(result.schedule).assignments).map(row=>({...row,task_id:row.task_id??row.sourceTaskId,model:row.model??row.configuredModelId,start:row.start??row.startSeconds,finish:row.finish??row.finishSeconds,cost_microusd:row.cost_microusd??row.reservedCostMicrousd})),cases=records(result.cases),conflicts=records(result.conflicts);
 const decision=object(result.promotionDecision ?? result.heldoutPromotionDecision);
 const selection=object(result.trainingSelection),candidates=object(result.candidates);
 return <>
  <RepositoryConflictResults result={result}/>
  {result.planSha256!==undefined&&<div className="apex-boundary"><h3>Compiled plan · no workers dispatched</h3><p>Adapter readiness and prices are caller assertions. Activated executable review plans enforce dependencies, exact grants, budgets and configured resource slots. Scheduled start/finish times and deadlines remain estimates.</p></div>}
  {result.evolutionProtocol!==undefined&&<div className="apex-boundary"><h3>Algorithm configuration experiment</h3><p>Training selection: <strong>{String(selection.candidateId)}</strong>. Sealed fixtures remain unscored. Actual monetary cost is unknown.</p><div className="apex-table-wrap"><table><caption>Candidate evidence · synthetic weighted coverage</caption><thead><tr><th>Candidate</th><th>Train objective / oracle</th><th>Held-out objective / oracle</th><th>Held-out latency</th></tr></thead><tbody>{Object.entries(candidates).map(([id,value])=>{const candidate=object(value),splits=object(candidate.splits),train=object(splits.train),heldout=object(splits.heldout);return <tr key={id}><td>{id}</td><td>{String(train.meanObjectiveRatio??'Unknown')}</td><td>{String(heldout.meanObjectiveRatio??'Unknown')}</td><td>{typeof heldout.meanLatencyMs==='number'?`${heldout.meanLatencyMs.toFixed(3)} ms`:'Unknown'}</td></tr>;})}</tbody></table></div></div>}
  {cases.length>0&&<div className="apex-table-wrap"><table><caption>Measured local synthetic fixtures</caption><thead><tr><th>Experiment</th><th>Elapsed time</th><th>Result</th><th>Evidence</th></tr></thead><tbody>{cases.map(item=>{const detail=object(item.result),promotion=object(detail.promotionDecision);return <tr key={String(item.id)}><td>{String(item.id)}</td><td>{typeof item.elapsedMs==='number'?`${item.elapsedMs.toFixed(3)} ms`:'Unmeasured'}</td><td>{'promote' in promotion?(promotion.promote?'Promotion gate passed':'Promotion withheld'):String(detail.status||detail.algorithm||'Completed')}</td><td><details><summary>Inspect result</summary><pre className="apex-json">{JSON.stringify(detail,null,2)}</pre></details></td></tr>;})}</tbody></table></div>}
  {assignments.length>0&&<div className="apex-table-wrap"><table><caption>Planned model assignments · times are estimated seconds</caption><thead><tr><th>Task</th><th>Model</th><th>Start</th><th>Finish</th><th>Estimated cost</th></tr></thead><tbody>{assignments.map(row=><tr key={String(row.task_id)}><td>{String(row.task_id)}</td><td>{String(row.model)}</td><td>{String(row.start)} s</td><td>{String(row.finish)} s</td><td>{money(row.cost_microusd)}</td></tr>)}</tbody></table></div>}
  {Array.isArray(result.waves)&&<div><h3>Execution waves</h3><ol>{result.waves.map((wave,index)=><li key={index}>{Array.isArray(wave)?wave.join(' + '):'Invalid wave'}</li>)}</ol><p className="apex-note">Each wave waits for the preceding wave. These are planned groups, not running workers.</p></div>}
  {conflicts.length>0&&<div className="apex-table-wrap"><table><caption>Declared file conflicts</caption><thead><tr><th>First task</th><th>Second task</th><th>Shared files</th></tr></thead><tbody>{conflicts.map((row,index)=><tr key={index}><td>{String(row.first_task??row.firstTask)}</td><td>{String(row.second_task??row.secondTask)}</td><td>{Array.isArray(row.files)?row.files.join(', '):records(row.overlaps).map(overlap=>`${String(overlap.firstPath)} ↔ ${String(overlap.secondPath)}`).join(', ')||'Unknown'}</td></tr>)}</tbody></table></div>}
  {'promote' in decision&&<div className="apex-boundary"><h3>{decision.promote?'Promotion gate passed':'Promotion withheld'}</h3><p>{Array.isArray(decision.failures)?decision.failures.map(value=>String(value).replaceAll('_',' ')).join('; '):''}</p><p>Baseline lower cost bound: {money(decision.baselineCostPerAcceptedMicrousdLowerBound)} / accepted outcome. Candidate upper cost bound: {money(decision.candidateCostPerAcceptedMicrousdUpperBound)} / accepted outcome. Bounds require sufficient supplied evaluator evidence and an identified spend cap.</p></div>}
 </>;
}
