'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Download,Save,Upload,Plus,ShieldCheck} from 'lucide-react';
import ScopeTopology from './ScopeTopology';
import SpecialistEditor from './SpecialistEditor';
import SpecialistActivation from './SpecialistActivation';
import {createStarterDesign,validateSpecialistDesign,previewSpecialistAccess,type SpecialistDesign,type Specialist,type ScopeNode} from '@/lib/specialist-design';
import {identityEvidence} from '@/lib/identity-evidence';
import styles from './SpecialistDesigner.module.css';
const draftKey='apexgraphswarm.specialists.design.v1';
const nodeKinds:ScopeNode['kind'][]=['repository','module','swarm','datacenter','rack','fleet','device','iot-center'];
function newId(prefix:string){return `${prefix}-${crypto.randomUUID().slice(0,8)}`;}
function exportJSON(design:SpecialistDesign){const url=URL.createObjectURL(new Blob([JSON.stringify(design,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='apex-specialist-design.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function SpecialistDesigner(){
 const [design,setDesign]=useState(createStarterDesign);
 const [nodeId,setNodeId]=useState(()=>createStarterDesign().nodes[0].id);
 const [agentId,setAgentId]=useState(()=>createStarterDesign().agents[0]?.id||'');
 const [teamId,setTeamId]=useState(()=>createStarterDesign().teams[0]?.id||'');
 const [message,setMessage]=useState(''),[agentSearch,setAgentSearch]=useState('');
 const [nodeLabel,setNodeLabel]=useState(''),[nodeKind,setNodeKind]=useState<ScopeNode['kind']>('swarm');
 const [pendingSource,setPendingSource]=useState<{id:string;label:string;repository:string}|null>(null);
 const [previewAction,setPreviewAction]=useState('read'),[previewAudience,setPreviewAudience]=useState(''),[previewPurpose,setPreviewPurpose]=useState(''),[elapsed,setElapsed]=useState(0),[approvers,setApprovers]=useState('');
 const [decision,setDecision]=useState<ReturnType<typeof previewSpecialistAccess>|null>(null);
 const validation=useMemo(()=>validateSpecialistDesign(design),[design]);
 const node=design.nodes.find(item=>item.id===nodeId)||design.nodes[0];
 const agent=design.agents.find(item=>item.id===agentId);
 const team=design.teams.find(item=>item.id===teamId);
 useEffect(()=>{try{const saved=localStorage.getItem(draftKey);if(saved)importText(saved);}catch{setMessage('Saved draft could not be loaded. The starter design is shown; the saved data was not overwritten.');}},[]);
 useEffect(()=>{try{const hash=new URLSearchParams(window.location.hash.slice(1));const raw=hash.get('source');if(!raw||raw.length>6000)return;const value=JSON.parse(raw);if(value&&typeof value.id==='string'&&value.id.length<=2000&&typeof value.label==='string'&&value.label.length<=200&&typeof value.repository==='string'&&value.repository.length<=500)setPendingSource(value);}catch{/* Invalid source context never changes the design. */}},[]);
 useEffect(()=>setDecision(null),[design,nodeId,agentId,previewAction,previewAudience,previewPurpose,elapsed,approvers]);
 function replaceDesign(next:SpecialistDesign){setDesign(next);setNodeId(next.nodes[0].id);setAgentId(next.agents[0]?.id||'');setTeamId(next.teams[0]?.id||'');setDecision(null);}
 function importText(raw:string){if(raw.length>524288)throw new Error('Design import exceeds 512 KiB.');const result=validateSpecialistDesign(JSON.parse(raw));if(!result.valid||!result.design)throw new Error(result.errors.slice(0,3).join(' '));replaceDesign(result.design);setMessage('Validated design loaded. No identities, permissions or infrastructure were provisioned.');}
 function loadSaved(){try{const raw=localStorage.getItem(draftKey);if(!raw)throw new Error('No saved specialist design in this browser.');importText(raw);}catch(error){setMessage(error instanceof Error?error.message:'Could not load design');}}
 function save(){if(!validation.valid)return;try{localStorage.setItem(draftKey,JSON.stringify(design));setMessage('Design metadata saved in this browser. No credentials were issued.');}catch{setMessage('Browser storage is unavailable. Export the design instead.');}}
 function changeAgent(next:Specialist){setDesign(current=>({...current,agents:current.agents.map(item=>item.id===next.id?next:item)}));}
 function structuralChange(next:SpecialistDesign){const result=validateSpecialistDesign(next);if(!result.valid){setMessage(result.errors.slice(0,3).join(' '));return false;}setDesign(next);setMessage('Design updated; execution permissions are unchanged.');return true;}
 function addNode(label=nodeLabel,externalRef='',kind=nodeKind){const id=newId('scope');const next={...design,nodes:[...design.nodes,{id,label:label.trim(),kind,parentId:node.id,teamIds:[],externalRef}]};if(structuralChange(next)){setNodeId(id);setNodeLabel('');return true;}return false;}
 function addTemplate(kind:'datacenter'|'fleet'|'iot-center'){
  const labels=kind==='datacenter'?['Planned data center','Rack A','Operations swarm']:kind==='fleet'?['Planned physical fleet','Device A','Device specialist swarm']:['Planned IoT command center','Sensor fleet','Sensor A'];
  const kinds:ScopeNode['kind'][]=kind==='datacenter'?['datacenter','rack','swarm']:kind==='fleet'?['fleet','device','swarm']:['iot-center','fleet','device'];
  const ids=labels.map(()=>newId('scope'));
  const added=labels.map((label,index)=>({id:ids[index],label,kind:kinds[index],parentId:index===0?node.id:ids[index-1],teamIds:[],externalRef:''}));
  if(structuralChange({...design,nodes:[...design.nodes,...added]}))setNodeId(ids[0]);
 }
 function removeNode(){if(node.parentId===null||design.nodes.some(item=>item.parentId===node.id))return;const parent=node.parentId;const next={...design,nodes:design.nodes.filter(item=>item.id!==node.id),agents:design.agents.map(item=>({...item,policy:{...item.policy,resourceIds:item.policy.resourceIds.filter(id=>id!==node.id)}}))};if(structuralChange(next))setNodeId(parent);}
 function removeAgent(){if(!agent||design.agents.length<=1)return;const next={...design,agents:design.agents.filter(item=>item.id!==agent.id),teams:design.teams.map(item=>({...item,agentIds:item.agentIds.filter(id=>id!==agent.id)}))};if(structuralChange(next))setAgentId(next.agents[0].id);}
 function removeTeam(){if(!team||design.teams.length<=1)return;const next={...design,teams:design.teams.filter(item=>item.id!==team.id),nodes:design.nodes.map(item=>({...item,teamIds:item.teamIds.filter(id=>id!==team.id)}))};if(structuralChange(next))setTeamId(next.teams[0].id);}
 function addAgent(){const template=createStarterDesign().agents[0];const id=newId('specialist');const next={...template,id,name:'New specialist',role:'Define a precise responsibility and acceptance criteria.',skills:[],tools:[],policy:{...template.policy,subjectRef:id,actions:[],resourceIds:[]}};if(structuralChange({...design,agents:[...design.agents,next]}))setAgentId(id);}
 function addTeam(){const id=newId('team');if(structuralChange({...design,teams:[...design.teams,{id,name:'New specialist swarm',agentIds:[]}]}))setTeamId(id);}
 function simulate(){if(!validation.valid)return;setDecision(previewSpecialistAccess(design,{agentId,nodeId:node.id,action:previewAction,audience:previewAudience,purpose:previewPurpose,elapsedSeconds:elapsed,approverIds:approvers.split(',').map(value=>value.trim()).filter(Boolean)}));}
 return <>
  <div className={styles.boundary}><ShieldCheck size={22}/><div><strong>Design and authorization review</strong><p>Customize specialists and attach teams to explicit graph scopes. Export a reviewed task for local operator activation. Authenticated approvals and exact task contracts are enforced by the control plane; this browser does not issue credentials or grant access. Data-center and physical-fleet connections remain design references.</p></div></div>
  <section className="apex-panel"><div className="apex-panel-heading"><div><h2>{design.name}</h2><p>{design.agents.length} specialists · {design.teams.length} teams · {design.nodes.length} scope nodes</p></div><span className="pill">No runtime authority</span></div><label className={styles.wideLabel}>Design name<input maxLength={120} value={design.name} onChange={event=>setDesign({...design,name:event.target.value})}/></label>
   <div className="apex-actions"><button className="primary-button" disabled={!validation.valid} onClick={save}><Save size={14}/>Save browser draft</button><button className="secondary-button" onClick={loadSaved}>Load browser draft</button><button className="secondary-button" disabled={!validation.valid} onClick={()=>exportJSON(design)}><Download size={14}/>Export design</button><label className={styles.import}><Upload size={14}/>Import design JSON<input type="file" accept="application/json,.json" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{if(file.size>524288)throw new Error('Design import exceeds 512 KiB.');importText(await file.text());}catch(error){setMessage(error instanceof Error?error.message:'Invalid design file.');}event.target.value='';}}/></label></div><p role="status" className="apex-note">{message}</p>
   {!validation.valid&&<div role="alert" className={styles.errors}><strong>Resolve design constraints before saving, export or preview.</strong><ul>{validation.errors.slice(0,6).map((error,index)=><li key={index}>{error}</li>)}</ul></div>}
   <p className="apex-note">References and labels are saved/exported as design metadata. Use non-secret identity and resource identifiers. Keep keys, tokens and private connection strings in a future server-side credential broker.</p>
  </section>
  {pendingSource&&<section className={styles.sourceBanner}><div><strong>Graph Studio node: {pendingSource.label}</strong><p>{pendingSource.repository} · {pendingSource.id}</p></div><button className="secondary-button" onClick={()=>{if(addNode(pendingSource.label,`graph:${pendingSource.repository}:${pendingSource.id}`,'module'))setPendingSource(null);}}>Attach beneath selected scope</button></section>}
  <section className="apex-panel" id="topology"><div className="apex-panel-heading"><div><h2>Scope graph & dedicated swarms</h2><p>Drill into a repository, service, data center, fleet or device. Scope relationships express organization; they do not inherit permissions.</p></div><Link className="secondary-button" href="/graph">Bind a Graph Studio node →</Link></div>
   <div className="apex-actions" style={{marginBottom:18}}><button className="secondary-button" disabled={design.nodes.length>297} onClick={()=>addTemplate('datacenter')}>Add data-center structure</button><button className="secondary-button" disabled={design.nodes.length>297} onClick={()=>addTemplate('fleet')}>Add physical-fleet structure</button><button className="secondary-button" disabled={design.nodes.length>297} onClick={()=>addTemplate('iot-center')}>Add IoT structure</button></div>
   <ScopeTopology nodes={design.nodes} selectedId={node.id} onSelect={setNodeId}/>
   <div className={styles.nodeInspector}><div><span className="eyebrow">SELECTED SCOPE / {node.kind}</span><h3>{node.label}</h3><code>{node.id}</code></div><div className="apex-form-grid"><label>Scope label<input value={node.label} maxLength={120} onChange={event=>setDesign({...design,nodes:design.nodes.map(item=>item.id===node.id?{...item,label:event.target.value}:item)})}/></label><label>External/private system reference<input value={node.externalRef} maxLength={2048} onChange={event=>setDesign({...design,nodes:design.nodes.map(item=>item.id===node.id?{...item,externalRef:event.target.value}:item)})} placeholder="Opaque asset/repository reference, not credentials"/></label>{node.parentId!==null&&<label>Parent scope<select value={node.parentId} onChange={event=>structuralChange({...design,nodes:design.nodes.map(item=>item.id===node.id?{...item,parentId:event.target.value}:item)})}>{design.nodes.filter(item=>item.id!==node.id).map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>}</div>
    <fieldset className={styles.fieldset}><legend>Dedicated teams assigned to this scope</legend>{design.teams.map(item=><label key={item.id}><input type="checkbox" checked={node.teamIds.includes(item.id)} onChange={event=>setDesign({...design,nodes:design.nodes.map(scope=>scope.id===node.id?{...scope,teamIds:event.target.checked?[...scope.teamIds,item.id]:scope.teamIds.filter(id=>id!==item.id)}:scope)})}/>{item.name} · {item.agentIds.length} specialists</label>)}</fieldset>
    <div className="apex-form-grid"><label>New child scope label<input value={nodeLabel} maxLength={120} onChange={event=>setNodeLabel(event.target.value)} placeholder="Example: rack A or inspection fleet"/></label><label>New child scope type<select value={nodeKind} onChange={event=>setNodeKind(event.target.value as ScopeNode['kind'])}>{nodeKinds.map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></label></div><div className="apex-actions"><button className="secondary-button" disabled={!nodeLabel.trim()||design.nodes.length>=300} onClick={()=>addNode()}><Plus size={14}/>Add child scope</button><button className="secondary-button" disabled={node.parentId===null||design.nodes.some(item=>item.parentId===node.id)} onClick={removeNode}>Remove leaf scope</button></div>
   </div>
  </section>
  <section className="apex-panel" id="teams"><div className="apex-panel-heading"><div><h2>Build specialist teams</h2><p>Reuse specialists across teams. Team membership and resource authority are evaluated separately.</p></div><button className="secondary-button" disabled={design.teams.length>=64} onClick={addTeam}><Plus size={14}/>Add team</button></div>
   <div className="apex-form-grid"><label>Edit team<select value={teamId} onChange={event=>setTeamId(event.target.value)}>{design.teams.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{team&&<label>Team name<input value={team.name} maxLength={120} onChange={event=>setDesign({...design,teams:design.teams.map(item=>item.id===team.id?{...item,name:event.target.value}:item)})}/></label>}</div>
   {team&&<div className="apex-actions"><button className="secondary-button" disabled={design.teams.length<=1} onClick={removeTeam}>Remove selected team</button></div>}
   {team&&<fieldset className={styles.fieldset}><legend>Team members</legend><div className={styles.scrollList}>{design.agents.map(item=><label key={item.id}><input type="checkbox" checked={team.agentIds.includes(item.id)} onChange={event=>setDesign({...design,teams:design.teams.map(member=>member.id===team.id?{...member,agentIds:event.target.checked?[...member.agentIds,item.id]:member.agentIds.filter(id=>id!==item.id)}:member)})}/>{item.name}</label>)}</div></fieldset>}
  </section>
  <section className="apex-panel" id="specialists"><div className="apex-panel-heading"><div><h2>Specialist capabilities & authority</h2><p>Start with explicit, narrow assignments. Every skill and tool binding remains a reviewed declaration until an enforcing adapter is connected.</p></div><button className="secondary-button" disabled={design.agents.length>=300} onClick={addAgent}><Plus size={14}/>Add specialist</button></div>
   <div className="apex-actions" style={{marginBottom:18}}><button className="secondary-button" disabled={!agent||design.agents.length<=1} onClick={removeAgent}>Remove selected specialist</button></div>
   <div className={styles.specialistLayout}><aside className={styles.agentList}><label>Find a specialist<input value={agentSearch} onChange={event=>setAgentSearch(event.target.value)}/></label>{design.agents.filter(item=>`${item.name} ${item.role}`.toLowerCase().includes(agentSearch.toLowerCase())).map(item=><button key={item.id} aria-pressed={agentId===item.id} onClick={()=>setAgentId(item.id)}><strong>{item.name}</strong><small>{item.skills.length} skills · {item.tools.length} tools · {item.policy.provider}</small></button>)}</aside>{agent?<SpecialistEditor key={agent.id} agent={agent} nodes={design.nodes} onChange={changeAgent}/>:<p>Select or create a specialist.</p>}</div>
  </section>
  <section className="apex-panel" id="authorization"><div className="apex-panel-heading"><div><h2>Preview an authorization request</h2><p>Checks exact assignment, scope, audience, purpose, expiry and declared approvals. Approver IDs are unverified simulation inputs; they never grant live authority.</p></div><span className="pill">Execution always disabled</span></div>
   <div className="apex-form-grid"><label>Requesting specialist<select value={agentId} onChange={event=>setAgentId(event.target.value)}>{design.agents.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Target scope<select value={node.id} onChange={event=>setNodeId(event.target.value)}>{design.nodes.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Requested action<select value={previewAction} onChange={event=>setPreviewAction(event.target.value)}>{['read','plan','administer','actuate'].map(action=><option key={action} value={action}>{action}</option>)}</select></label><label>Request audience<input value={previewAudience} onChange={event=>setPreviewAudience(event.target.value)}/></label><label>Request purpose<input value={previewPurpose} onChange={event=>setPreviewPurpose(event.target.value)}/></label><label>Elapsed grant time (seconds)<input type="number" min="0" value={elapsed} onChange={event=>setElapsed(Number(event.target.value))}/></label><label>Distinct approver IDs (comma-separated)<input value={approvers} onChange={event=>setApprovers(event.target.value)}/></label></div>
   <div className="apex-actions"><button className="primary-button" disabled={!validation.valid||!agent} onClick={simulate}>Preview access decision</button></div>{decision&&<div role="status" className={styles.decision}><strong>{decision.decision}</strong><p>Execution allowed: no</p><ul>{decision.reasons.map((reason,index)=><li key={index}>{reason}</li>)}</ul></div>}
  </section>
  <SpecialistActivation key={`${agentId}:${node.id}`} design={design} specialistId={agentId} nodeId={node.id}/>
  <section className="apex-panel"><div className="apex-panel-heading"><div><h2>Your identity projects & future adapters</h2><p>Source evidence and implementation boundaries. No access to unnamed private repositories is needed for this design.</p></div></div><div className={styles.identityCards}>{identityEvidence.map(item=><article key={item.id}><h3>{item.name}</h3><p>{item.status}</p><small>Revision: {item.revision||'Not verified'}</small><details><summary>Controls, limits and adoption</summary><ul>{item.capabilities.map(value=><li key={value}>{value}</li>)}</ul><h4>Current limits</h4><ul>{item.limits.map(value=><li key={value}>{value}</li>)}</ul><p>{item.adoption}</p></details><a href={item.source} target="_blank" rel="noreferrer">Source repository ↗</a></article>)}</div><p className="apex-note">Private data-center, Physical AI and IoT integrations can later map stable asset identities, telemetry schemas, command capabilities, approval policies and revocation signals to these nodes. Credentials and physical-command enforcement stay outside the visualization.</p></section>
 </>;
}
