'use client';
import {useState} from 'react';
import {downloadJSON} from '@/lib/graph';
import type {SpecialistDesign} from '@/lib/specialist-design';
import {executableReviewTasks,specialistActivationRequest,type ExecutableReviewTask} from '@/lib/specialist-activation';
export default function SpecialistActivation({design,specialistId,nodeId}:{design:SpecialistDesign;specialistId:string;nodeId:string}){
 const [tasks,setTasks]=useState<ExecutableReviewTask[]>([]),[taskId,setTaskId]=useState(''),[worker,setWorker]=useState(''),[action,setAction]=useState('read'),[toolIndex,setToolIndex]=useState(0),[message,setMessage]=useState(''),[error,setError]=useState('');
 const agent=design.agents.find(item=>item.id===specialistId),task=tasks.find(item=>item.id===taskId);
 async function load(file:File){setError('');setMessage('');try{if(file.size>1500000)throw Error('Import exceeds 1.5 MB.');const next=executableReviewTasks(JSON.parse(await file.text()));setTasks(next);setTaskId(next[0].id);setMessage(`Loaded ${next.length} executable review task(s). Nothing was activated.`);}catch(error){setTasks([]);setTaskId('');setError(error instanceof Error?error.message:'Invalid plan.');}}
 function exportRequest(){setError('');try{if(!task||!agent?.tools[toolIndex])throw Error('Select a task and a declared tool binding.');const request=specialistActivationRequest(design,task,{specialistId,nodeId,action,workerId:worker,mcpBinding:agent.tools[toolIndex],idempotencyKey:crypto.randomUUID()});downloadJSON('apex-specialist-contract-request.json',request);setMessage('Review request exported. A local operator must create it, collect authenticated approvals, activate it, and bind the returned contract to this plan. No credentials or grants were issued.');}catch(error){setError(error instanceof Error?error.message:'Could not export request.');}}
 return <section className="apex-panel" aria-label="Specialist execution handoff"><div className="apex-panel-heading"><div><h2>Bind a reviewed task to this specialist</h2><p>Import an executable review plan to prepare a precise operator handoff. Approval covers its exact stored goal and graph snapshot.</p></div><span className="pill">Operator activation required</span></div>
 <p>Selected specialist: <strong>{agent?.name||'None'}</strong> · Scope: <strong>{design.nodes.find(node=>node.id===nodeId)?.label||'None'}</strong></p>
 <div className="apex-form-grid"><label>Compiled executable plan or evidence export<input type="file" accept="application/json,.json" onChange={event=>{const file=event.target.files?.[0];if(file)void load(file);event.target.value='';}}/></label><label>Stored task<select value={taskId} onChange={event=>setTaskId(event.target.value)}><option value="">Import a compiled plan</option>{tasks.map(item=><option key={item.id} value={item.id}>{item.payload.sourceTaskId||item.id}</option>)}</select></label><label>Exact enrolled worker ID<input value={worker} onChange={event=>setWorker(event.target.value)} placeholder="Operator-provisioned worker"/></label><label>Contract action<select value={action} onChange={event=>setAction(event.target.value)}><option value="read">read</option><option value="plan">plan</option></select></label><label>Declared tool binding<select value={toolIndex} onChange={event=>setToolIndex(Number(event.target.value))}>{!agent?.tools.length&&<option value={0}>Add a tool declaration above</option>}{agent?.tools.map((tool,index)=><option key={`${tool.serverId}/${tool.toolName}/${tool.gatewayId}`} value={index}>{tool.gatewayId} / {tool.serverId} / {tool.toolName}</option>)}</select></label></div>
 {task&&<details><summary>Inspect the exact task input before requesting approval</summary><pre className="apex-json">{JSON.stringify(task.payload.execution.input,null,2)}</pre></details>}
 <div className="apex-actions"><button className="secondary-button" disabled={!task||!agent?.tools.length||!worker} onClick={exportRequest}>Export operator review request</button></div>
 <p className="apex-note">Preview approver IDs do not count as authenticated approvals. The local contract service revalidates the design, exact assignment, worker, input, TTL and quorum. Skills and MCP bindings are provenance declarations; this handoff does not install or invoke them. Exported expiry is limited by the specialist TTL, so process a fresh request promptly.</p>
 {message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error-text">{error}</p>}
 </section>;
}
