/**
 * React component for specialist editor.
 *
 * @module SpecialistEditor
 * @packageDocumentation
 */
'use client';
import {useState} from 'react';
import Link from 'next/link';
import type {Specialist,ScopeNode,SkillBinding,ToolBinding} from '@/lib/specialist-design';
import {harnessCatalog} from '@/lib/harness-catalog';
import styles from './SpecialistDesigner.module.css';
const emptySkill:SkillBinding={id:'',sourceUrl:'',revision:'',sha256:''};
const emptyTool:ToolBinding={serverId:'',toolName:'',gatewayId:''};
export default function SpecialistEditor({agent,nodes,onChange}:{agent:Specialist;nodes:readonly ScopeNode[];onChange:(agent:Specialist)=>void}){
 const [skill,setSkill]=useState<SkillBinding>(emptySkill),[tool,setTool]=useState<ToolBinding>(emptyTool);
 const [profiles,setProfiles]=useState<{id:string;label:string}[]>([]),[message,setMessage]=useState('');
 function policy<K extends keyof Specialist['policy']>(key:K,value:Specialist['policy'][K]){onChange({...agent,policy:{...agent.policy,[key]:value}});}
 async function loadProfiles(){try{const response=await fetch('/api/ecosystem/mcp',{cache:'no-store'});const result=await response.json();if(!response.ok||result.configurationError)throw new Error(result.configurationError||'Could not load profiles');setProfiles(result.servers);setMessage(result.servers.length?'Configured profile IDs loaded. Tool declarations still need independent review.':'No server profiles configured. References below remain design declarations.');}catch(error){setMessage(error instanceof Error?error.message:'Could not load profiles');}}
 return <div className={styles.agentEditor}><p className="apex-note"><Link href="/delegation">Compare model/harness costs and capability constraints →</Link></p>
  <div className="apex-form-grid"><label>Specialist name<input value={agent.name} maxLength={120} onChange={e=>onChange({...agent,name:e.target.value})}/></label><label>Harness<select value={agent.harnessId} onChange={e=>onChange({...agent,harnessId:e.target.value})}>{!['openrouter','vllm'].includes(agent.harnessId)&&!harnessCatalog.some(item=>item.id===agent.harnessId)&&<option value={agent.harnessId}>{agent.harnessId||'Unassigned'}</option>}{harnessCatalog.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}<option value="openrouter">OpenRouter · direct review adapter</option><option value="vllm">vLLM · direct review adapter</option></select></label><label>Model / provider reference<input value={agent.modelRef} onChange={e=>onChange({...agent,modelRef:e.target.value})} placeholder="Provider/model revision — no API keys"/></label></div>
  <label className={styles.wideLabel}>Precise responsibility and acceptance criteria<textarea rows={3} value={agent.role} onChange={e=>onChange({...agent,role:e.target.value})}/></label>
  <details open><summary>Skills & library provenance · {agent.skills.length}</summary><p className="apex-note">Bind reviewed skill identities to this specialist. A revision and content hash identify the intended artifact; they do not prove trust or installation. <Link href="/ecosystem#skills">Review SKILL.md →</Link> · <a href="https://skills.sh" target="_blank" rel="noreferrer">Browse skills.sh ↗</a></p>
   {agent.skills.map((binding,index)=><div className={styles.binding} key={`${binding.id}-${index}`}><div><strong>{binding.id}</strong><small>{binding.sourceUrl} · {binding.revision}</small><code>{binding.sha256}</code></div><button className="secondary-button" onClick={()=>onChange({...agent,skills:agent.skills.filter((_,i)=>i!==index)})} aria-label={`Remove skill ${binding.id}`}>Remove</button></div>)}
   <div className="apex-form-grid"><label>Skill ID<input value={skill.id} onChange={e=>setSkill({...skill,id:e.target.value})} placeholder="repository-review"/></label><label>Skill library / source URL<input value={skill.sourceUrl} onChange={e=>setSkill({...skill,sourceUrl:e.target.value})} placeholder="https://github.com/owner/library/…"/></label><label>Pinned skill revision<input value={skill.revision} onChange={e=>setSkill({...skill,revision:e.target.value})}/></label><label>Skill content SHA-256<input value={skill.sha256} maxLength={64} onChange={e=>setSkill({...skill,sha256:e.target.value})}/></label></div>
   <button className="secondary-button" disabled={agent.skills.length>=32||!skill.id||!skill.sourceUrl||!skill.revision||!/^[a-fA-F0-9]{64}$/.test(skill.sha256)} onClick={()=>{onChange({...agent,skills:[...agent.skills,{...skill,sha256:skill.sha256.toLowerCase()}]});setSkill(emptySkill);}}>Bind skill reference</button>
  </details>
  <details><summary>MCP tools & gateways · {agent.tools.length}</summary><p className="apex-note">Assign exact server/tool identities. Gateway assignment does not grant every tool behind the gateway. <Link href="/ecosystem#mcp">Discover configured tools →</Link></p>
   <button className="secondary-button" onClick={loadProfiles}>Load configured MCP profile IDs</button><p role="status" className="apex-note">{message}</p>
   {agent.tools.map((binding,index)=><div className={styles.binding} key={`${binding.serverId}-${binding.toolName}-${index}`}><div><strong>{binding.serverId} / {binding.toolName}</strong><small>Gateway: {binding.gatewayId||'Direct server'}</small></div><button className="secondary-button" onClick={()=>onChange({...agent,tools:agent.tools.filter((_,i)=>i!==index)})} aria-label={`Remove tool ${binding.toolName}`}>Remove</button></div>)}
   <div className="apex-form-grid"><label>MCP server ID<input list={`mcp-profiles-${agent.id}`} value={tool.serverId} onChange={e=>setTool({...tool,serverId:e.target.value})}/><datalist id={`mcp-profiles-${agent.id}`}>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.label}</option>)}</datalist></label><label>Exact tool name<input value={tool.toolName} onChange={e=>setTool({...tool,toolName:e.target.value})}/></label><label>Gateway ID (optional)<input value={tool.gatewayId} onChange={e=>setTool({...tool,gatewayId:e.target.value})}/></label></div>
   <button className="secondary-button" disabled={agent.tools.length>=32||!tool.serverId||!tool.toolName} onClick={()=>{onChange({...agent,tools:[...agent.tools,tool]});setTool(emptyTool);}}>Bind tool reference</button>
  </details>
  <details open><summary>IAM / PAM policy intent</summary><p className="apex-note">This is a policy-design record, not a credential or an enforced grant. Existing execution endpoints retain their current controls.</p>
   <div className="apex-form-grid"><label>Identity / privilege adapter<select value={agent.policy.provider} onChange={e=>policy('provider',e.target.value as Specialist['policy']['provider'])}><option value="agentiam-lab">AgentIAM reference lab</option><option value="agent-jit-iam">Agent JIT IAM · pending adapter</option><option value="external">External IAM / PAM adapter</option></select></label>{([['subjectRef','Agent identity reference'],['ownerRef','Accountable owner reference'],['tenantRef','Tenant / trust domain'],['audience','Target audience'],['purpose','Authorized purpose']] as const).map(([key,label])=><label key={key}>{label}<input value={agent.policy[key]} onChange={e=>policy(key,e.target.value)}/></label>)}<label>Requested TTL (seconds)<input type="number" min="1" max="300" value={agent.policy.ttlSeconds} onChange={e=>policy('ttlSeconds',Number(e.target.value))}/></label><label>Maximum delegation depth<input type="number" min="0" max="8" value={agent.policy.maxDelegationDepth} onChange={e=>policy('maxDelegationDepth',Number(e.target.value))}/></label><label>Approval quorum<input type="number" min="0" max="8" value={agent.policy.approvalQuorum} onChange={e=>policy('approvalQuorum',Number(e.target.value))}/></label></div>
   <fieldset className={styles.fieldset}><legend>Requested actions (exact matches)</legend>{['read','plan','administer','actuate',...agent.policy.actions.filter(action=>!['read','plan','administer','actuate'].includes(action))].map(action=><label key={action}><input type="checkbox" checked={agent.policy.actions.includes(action)} onChange={e=>policy('actions',e.target.checked?[...agent.policy.actions,action]:agent.policy.actions.filter(item=>item!==action))}/>{action}</label>)}</fieldset>
   <fieldset className={styles.fieldset}><legend>Explicit resource scope · no descendant inheritance</legend><div className={styles.scrollList}>{nodes.map(node=><label key={node.id}><input type="checkbox" checked={agent.policy.resourceIds.includes(node.id)} onChange={e=>policy('resourceIds',e.target.checked?[...agent.policy.resourceIds,node.id]:agent.policy.resourceIds.filter(id=>id!==node.id))}/>{node.label} <small>{node.kind}</small></label>)}</div></fieldset>
   <p className="apex-note">Administrative and physical actuation requests remain denied in this designer. Live enforcement needs an authenticated decision point, JIT credential broker, revocation and audit receipts; physical systems also need independent safety controls. Delegation depth is a declared future adapter constraint.</p>
  </details>
 </div>;
}
